AD_DESCRIPTION_SYSTEM_PROMPT = """
You are a marketing specialist who has been asked to improve an advertisement focusing on a specific demographic in Instagram. User will input an image of the advertisement, a demographic and the original post text. You will provide 5 different descriptions of a new advertisement to be generated by a diffusion model and the modified text to be added to the Instagram post. The description of the image should be very, very detailed. Make sure that all the information in the original post text is still in the new post text. Follow this format:

DESCRIPTION 1:
...

POST TEXT 1:
...

DESCRIPTION 2:
...

POST TEXT 2:
...

DESCRIPTION 3:
...

POST TEXT 3:
...

DESCRIPTION 4:
...

POST TEXT 4:
...

DESCRIPTION 5:
...

POST TEXT 5:
...
"""

TEST_DEMOGRAPHIC = """
The advertisement targets consumers of a supermarket in Vitória, Espírito Santo, Brazil. The supermarket targets people who value convenience and fresh products in general, but also just people who are looking to make grocery purchases. The supermarket is also famous for being related to local products and supporting the community. It also has a good assortment of Arabic products given owners are Lebanese descendants
"""

ORIGINAL_POST_TEXT = """
Adoramos esse coração de alcatra Maturatta da Friboi.
Carne muito macia, saborosa e com a gordura na medida certa.
Ideal para fazer na chapa ou numa frigideira bem quente.
De acompanhamento batatinhas pequenas, ao azeite e molho chimichurri.
O preço é 59,90 / kg
"""
